# Note: The secrets need to be stored in a file called "secrets.toml" inside ".streamlit"

# Everything in this section will be available as an environment variable
base_url = "http://localhost:5000"
